[package]
name = "vingress"
version = "0.1.6"
edition = "2021"

[profile.release]
strip = true
lto = true
opt-level="z"
codegen-units = 1

[dependencies]
kube = { version = "0.92.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.22.0", features = ["latest"] }
tokio = { version = "1.38.1", features = ["full"] }
futures = { version = "0.3.17", default-features = false }
handlebars = "6.0.0"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
env_logger = "0.11.5"
log = "0.4.22"
clap = {version = "4.5.11", features = ["derive"]}
