FROM rust:1.91-alpine AS builder

RUN apk add --no-cache musl-dev build-base upx

COPY Cargo.toml Cargo.lock ./
COPY src src
COPY template/vcl.hbs template/vcl.hbs

RUN cargo b
RUN upx ./target/debug/vingress


FROM varnish:8.0-alpine AS release
LABEL maintainers="Varnish-Cache Friends"

USER root
WORKDIR controller
RUN apk add curl
RUN chown -R varnish:varnish /etc/varnish

USER varnish

COPY --from=builder ./template/vcl.hbs template/vcl.hbs
COPY --from=builder ./target/debug/vingress vingress-bin

ENTRYPOINT ["./vingress-bin"] 
CMD []
