apiVersion: apps/v1
kind: Deployment
metadata:
  name: smp-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smp-post
  template:
    metadata:
      labels:
        app: smp-post
    spec:
      containers:
        - name: smp-post
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: smp-post-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: smp-post
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smp
  template:
    metadata:
      labels:
        app: smp
    spec:
      containers:
        - name: smp
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: smp-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: smp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smp-ingress
  labels:
    kubernetes.io/ingress: varnish
spec:
  ingressClassName: varnish
  rules:
    - host: smp.example.com
      http:
        paths:
          - path: /post
            pathType: Prefix
            backend:
              service:
                name: smp-post-svc
                port:
                  number: 80
          - path: /smp
            pathType: Prefix
            backend:
              service:
                name: smp-svc
                port:
                  number: 80
