apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: varnish-ingress-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: varnish-ingress-controller
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: varnish-ingress-controller
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.hpa.maxReplicas | default 10 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage | default 60 }}

