apiVersion: v2
name: varnish-ingress-controller
description: A Helm chart for deploying the Varnish Ingress Controller
version: 0.4.0
appVersion: "0.5.0"
icon: https://varnish-cache.org/_static/varnish-bunny.png
home: https://varnish-cache.org
keywords:
  - kubernetes
  - helm
  - varnish
  - varnish-cache
  - ingress
maintainers:
  - name: Marius Magureanu
    email: mariusmagureanu@live.dk
sources:
  - https://github.com/mariusmagureanu/vingress
annotations:
  category: cluster
  artifacthub.io/category: networking
  artifacthub.io/prerelease: "true"
  artifacthub.io/signKey: |
    fingerprint: 4D3E36C33F431E0DD984C60CADB9F0C06D7F269D
    url: https://mariusmagureanu.github.io/vingress/charts/key/vingress.public.asc 
