apiVersion: v1
entries:
  varnish-ingress-controller:
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/prerelease: "true"
      category: cluster
    apiVersion: v2
    appVersion: 0.2.0
    created: "2024-09-02T23:07:10.405124917+02:00"
    description: A Helm chart for deploying the Varnish Ingress Controller
    digest: db19c8eaa64e78ba5cc68b143ebebec9620af00516bd2fd633d96a1d8887173e
    home: https://varnish-cache.org
    icon: https://varnish-cache.org/_static/varnish-bunny.png
    keywords:
    - kubernetes
    - helm
    - varnish
    - varnish-cache
    - ingress
    maintainers:
    - email: mariusmagureanu@live.dk
      name: Marius Magureanu
    name: varnish-ingress-controller
    urls:
    - https://mariusmagureanu.github.io/vingress/charts/varnish-ingress-controller-0.2.0.tgz
    version: 0.2.0
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/prerelease: "true"
      category: cluster
    apiVersion: v2
    appVersion: "0.1.0"
    created: "2024-09-02T23:07:10.404806728+02:00"
    description: A Helm chart for deploying the Varnish Ingress Controller
    digest: e9a8980dbbcbd58cd0a29847ac54fed8ff369f5685dd65bd3d774edcc60a473f
    home: https://varnish-cache.org
    icon: https://varnish-cache.org/_static/varnish-bunny.png
    keywords:
    - kubernetes
    - helm
    - varnish
    - varnish-cache
    - ingress
    maintainers:
    - email: mariusmagureanu@live.dk
      name: Marius Magureanu
    name: varnish-ingress-controller
    urls:
    - https://mariusmagureanu.github.io/vingress/charts/varnish-ingress-controller-0.1.0.tgz
    version: 0.1.0
generated: "2024-09-02T23:07:10.404333146+02:00"
