replicaCount: 1
image:
  controller:
    repository: mariusm/vingress
    tag: "0.2.1"
  pullPolicy: Always
serviceAccount:
  name: varnish-controller
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "2048Mi"
    cpu: "150m"
varnish:
  httpPort: "6081"
  vclFile: "/etc/varnish/default.vcl"
  workFolder: "/etc/varnish"
  params: ""
  defaultTtl: "120s"
service:
  type: ClusterIP
  port: 8081
  targetPort: 6081
