name: Build master
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Extract version from Cargo.toml
        id: cargo_version
        run: echo "VERSION=$(grep '^version' Cargo.toml | sed 's/version = \"\(.*\)\"/\1/')" >> $GITHUB_ENV
      - name: Log into Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
      - name: Build Docker image
        run: docker build -t vingress:$VERSION .
      - name: Tag Docker image with version
        run: docker tag vingress:$VERSION mariusm/vingress:$VERSION
      - name: Push Docker image
        run: docker push mariusm/vingress:$VERSION
